import { OfficerPersona } from "@/types";

export const PRECONFIGURED_PERSONAS: OfficerPersona[] = [
  {
    id: "forest",
    email: "forest.officer@uk.gov.in",
    password: "Shasan@2026",
    full_name: "Vikram Singh Negi",
    department: "Forest",
    designation: "Divisional Forest Officer (DFO)",
    role: "OFFICER",
    description: "Forest conservation, compensatory afforestation, tree felling & working plans.",
    badgeColor: "text-emerald-300 border-emerald-500/40",
    badgeBg: "bg-emerald-500/15",
  },
  {
    id: "finance",
    email: "finance.officer@uk.gov.in",
    password: "Shasan@2026",
    full_name: "Pooja Sharma",
    department: "Finance",
    designation: "Senior Accounts Officer",
    role: "OFFICER",
    description: "Financial sanction limits, treasury rules, DA revision orders & fiscal audits.",
    badgeColor: "text-amber-300 border-amber-500/40",
    badgeBg: "bg-amber-500/15",
  },
  {
    id: "personnel",
    email: "personnel.officer@uk.gov.in",
    password: "Shasan@2026",
    full_name: "Rajesh Chandra",
    department: "Personnel",
    designation: "Joint Secretary (Personnel)",
    role: "OFFICER",
    description: "State civil service rules, grade pay notifications, leave & seniority lists.",
    badgeColor: "text-purple-300 border-purple-500/40",
    badgeBg: "bg-purple-500/15",
  },
  {
    id: "itda_admin",
    email: "admin.itda@uk.gov.in",
    password: "Shasan@2026",
    full_name: "Amitabh Rawat",
    department: "General",
    designation: "Director (ITDA)",
    role: "ADMIN",
    description: "Multi-department search override, legal supersession audit & system governance.",
    badgeColor: "text-sky-300 border-sky-500/40",
    badgeBg: "bg-sky-500/15",
  },
];
